
server:
  port: 8086

spring:
  application:
    name: verify-api

eureka:
  client:
    service-url:
      defaultZone: http://hero:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
    # 默认 90 秒
    lease-expiration-duration-in-seconds: 5
    # 默认 30 秒
    lease-renewal-interval-in-seconds: 5

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh,health,info
