
server:
  port: 8086

spring:
  application:
    name: verify-api

eureka:
  client:
    service-url:
      defaultZone: http://hero:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}


